version: '3' #La versión del script YAML

services: #Declaramos los contenedores y servicios a utilizar
  basededatos: #El definimos el contenedor que será la base de datos, cogiendo las siguientes imágenes
    image: mysql:5.7
    restart: always
    ports: #Puertos que se utilizarán host:huésped
      - 8081:3306
    environment: #Variables de entorno
      MYSQL_USER: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_PASSWORD: wordpress
    #container_name: bd #le damos nombre único, si no, docker da ID y nombre aleatorios

  wordpress: #Definimos el contenedor de Wordpress
    depends_on: #De qué contenedores depende
      - basededatos
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: basededatos:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    #container_name: wp
 
  phpmyadmin: #Definimos el contenedor de phpMyAdmin
   depends_on: #De qué contenedores depende
    - basededatos
   image: phpmyadmin/phpmyadmin #Imagen oficial phpMyAdmin 
   restart: always
   ports:
    - 8084:80
   environment: #Variables de entorno
    PMA_HOST: basededatos #Contenedor host de la base de datos
    MYSQL_USER: wordpress
    MYSQL_PASSWORD: wordpress
    MYSQL_ROOT_PASSWORD: wordpress
   #container_name: pma